In [8]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt


In [9]:
df=pd.read_csv('C:/WORK/PROJECTS/HOME-CREDIT-RISK-AUTOMATION/data/clean/final_credit_risk_dataset.csv')

In [10]:
df.shape

(307511, 66)

In [11]:
df["DAYS_REGISTRATION"] = df["DAYS_REGISTRATION"].abs()
df["DAYS_ID_PUBLISH"] = df["DAYS_ID_PUBLISH"].abs()
df["DAYS_BIRTH"] = df["DAYS_BIRTH"].abs()
df["DAYS_EMPLOYED"] = df["DAYS_EMPLOYED"].abs()

In [12]:
df.head()

,target,CNT_FAM_MEMBERS,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,NAME_INCOME_TYPE_Commercial associate,NAME_INCOME_TYPE_Maternity leave,NAME_INCOME_TYPE_Pensioner,NAME_INCOME_TYPE_State servant,NAME_INCOME_TYPE_Student,NAME_INCOME_TYPE_Unemployed,NAME_INCOME_TYPE_Working,approval_behaviour_Mostly Rejected,loan_decision_type_Overpaid,loan_decision_type_Underpaid
0,1,1.0,9461,637,3648.0,2120,202500.0,406597.5,24700.5,351000.0,...,False,False,False,False,False,False,True,False,False,False
1,0,2.0,16765,1188,1186.0,291,270000.0,1293502.5,35698.5,1129500.0,...,False,False,False,True,False,False,False,False,True,False
2,0,1.0,19046,225,4260.0,2531,67500.0,135000.0,6750.0,135000.0,...,False,False,False,False,False,False,True,False,False,True
3,0,2.0,19005,3039,9833.0,2437,135000.0,312682.5,29686.5,297000.0,...,False,False,False,False,False,False,True,False,False,False
4,0,1.0,19932,3038,4311.0,3458,121500.0,513000.0,21865.5,513000.0,...,False,False,False,False,False,False,True,False,False,False


In [13]:


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 66 columns):
 #   Column                                             Non-Null Count   Dtype  
---  ------                                             --------------   -----  
 0   target                                             307511 non-null  int64  
 1   CNT_FAM_MEMBERS                                    307509 non-null  float64
 2   DAYS_BIRTH                                         307511 non-null  int64  
 3   DAYS_EMPLOYED                                      307511 non-null  int64  
 4   DAYS_REGISTRATION                                  307511 non-null  float64
 5   DAYS_ID_PUBLISH                                    307511 non-null  int64  
 6   AMT_INCOME_TOTAL                                   307511 non-null  float64
 7   AMT_CREDIT                                         307511 non-null  float64
 8   AMT_ANNUITY                                        307499 non-null  float6

creating target and features column and seperating them

In [14]:
x = df.drop("target", axis=1)
y = df["target"]

train test split

In [15]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

inf or zero conversion

In [16]:
np.isinf(x_train).sum().sum()

np.int64(1)

In [1]:
x_train = x_train.replace([np.inf, -np.inf], np.nan)
x_test = x_test.replace([np.inf, -np.inf], np.nan)

NameError: name 'x_train' is not defined

In [18]:
x_train = x_train.fillna(x_train.median())
x_test = x_test.fillna(x_test.median())

feature scaling

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

training the model for logistic regression

In [20]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight="balanced")
model.fit(X_train_scaled, y_train)

c:\WORK\PROJECTS\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",'balanced'
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :ter

predction and score 

In [21]:
y_pred = model.predict(X_test_scaled)

In [22]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.6946653008796319

Classification Report:

              precision    recall  f1-score   support

           0       0.96      0.70      0.81     56538
           1       0.16      0.68      0.27      4965

    accuracy                           0.69     61503
   macro avg       0.56      0.69      0.54     61503
weighted avg       0.90      0.69      0.76     61503


Confusion Matrix:

[[39325 17213]
 [ 1566  3399]]


creating multiple models to build a ensemble model for better scores

In [23]:

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [24]:

# Gradient Boosting
model_gb = GradientBoostingClassifier(
    n_estimators=150,
    learning_rate=0.05,
    random_state=42
)


# Random Forest
model_rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    class_weight="balanced",
    random_state=42
)

# Decision Tree
model_dt = DecisionTreeClassifier(
    max_depth=6,
    class_weight="balanced",
    random_state=42
)

In [28]:
np.isinf(x_train).sum().sum()

np.int64(0)

In [29]:
x_train = x_train.replace([np.inf, -np.inf], np.nan)
x_test = x_test.replace([np.inf, -np.inf], np.nan)

# fill missing values using median
x_train = x_train.fillna(x_train.median())
x_test = x_test.fillna(x_test.median())

In [31]:



# Random Forest
model_rf.fit(x_train, y_train)

# Gradient Boosting
model_gb.fit(x_train, y_train)

# Decision Tree
model_dt.fit(x_train, y_train)

,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",6
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",42
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current no

In [34]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

Feature selection

In [44]:
import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": x_train.columns,
    "Importance": model_rf.feature_importances_
})

feature_importance = feature_importance.sort_values(by="Importance", ascending=False)

print(feature_importance.head(50))

                                              Feature  Importance
42                                     ext_source_avg    0.293845
41                                       EXT_SOURCE_3    0.131194
40                                       EXT_SOURCE_2    0.118848
2                                       DAYS_EMPLOYED    0.047426
39                                       EXT_SOURCE_1    0.045109
19                             bureau_avg_days_credit    0.036382
11                                 credit_goods_ratio    0.029574
21                           bureau_debt_credit_ratio    0.025910
1                                          DAYS_BIRTH    0.024481
12                                   payment_capacity    0.020721
37                                approval_percentage    0.016675
27                                 late_payment_count    0.013494
38                        application_to_credit_ratio    0.012752
34                                 prev_refused_count    0.011788
51        

In [45]:
eature_importance = pd.DataFrame({
    "Feature": x_train.columns,
    "Importance": model_rf.feature_importances_
})

feature_importance = feature_importance.sort_values(by="Importance", ascending=False)

print(feature_importance.head(20))

                                              Feature  Importance
42                                     ext_source_avg    0.293845
41                                       EXT_SOURCE_3    0.131194
40                                       EXT_SOURCE_2    0.118848
2                                       DAYS_EMPLOYED    0.047426
39                                       EXT_SOURCE_1    0.045109
19                             bureau_avg_days_credit    0.036382
11                                 credit_goods_ratio    0.029574
21                           bureau_debt_credit_ratio    0.025910
1                                          DAYS_BIRTH    0.024481
12                                   payment_capacity    0.020721
37                                approval_percentage    0.016675
27                                 late_payment_count    0.013494
38                        application_to_credit_ratio    0.012752
34                                 prev_refused_count    0.011788
51        

In [46]:
important_features = feature_importance[
    feature_importance["Importance"] > 0.005
]["Feature"]

X_train_selected = x_train[important_features]
X_test_selected = x_test[important_features]

In [47]:
model_rf.fit(X_train_selected, y_train)
model.fit(X_train_selected, y_train)
model_dt.fit(X_train_selected, y_train)

c:\WORK\PROJECTS\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",6
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",42
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current no

In [50]:
# Random Forest
y_pred_rf = model_rf.predict(X_test_selected)

# Gradient Boosting
y_pred_lr = model.predict(X_test_selected)

# Decision Tree
y_pred_dt = model_dt.predict(X_test_selected)

In [51]:
print("Logistic Regression")

print("Accuracy:", accuracy_score(y_test, y_pred_lr))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lr))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression
Accuracy: 0.6031738289189146

Classification Report:

              precision    recall  f1-score   support

           0       0.94      0.61      0.74     56538
           1       0.11      0.56      0.18      4965

    accuracy                           0.60     61503
   macro avg       0.53      0.58      0.46     61503
weighted avg       0.87      0.60      0.69     61503


Confusion Matrix:

[[34336 22202]
 [ 2204  2761]]


In [55]:
print("Decision Tree")

print("Accuracy:", accuracy_score(y_test, y_pred_dt))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dt))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_dt))

Decision Tree
Accuracy: 0.6583256101328391

Classification Report:

              precision    recall  f1-score   support

           0       0.96      0.66      0.78     56538
           1       0.15      0.69      0.25      4965

    accuracy                           0.66     61503
   macro avg       0.55      0.67      0.51     61503
weighted avg       0.89      0.66      0.74     61503


Confusion Matrix:

[[37075 19463]
 [ 1551  3414]]


In [53]:
print("Random Forest")

print("Accuracy:", accuracy_score(y_test, y_pred_rf))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest
Accuracy: 0.722338747703364

Classification Report:

              precision    recall  f1-score   support

           0       0.96      0.73      0.83     56538
           1       0.17      0.64      0.27      4965

    accuracy                           0.72     61503
   macro avg       0.57      0.68      0.55     61503
weighted avg       0.89      0.72      0.78     61503


Confusion Matrix:

[[41253 15285]
 [ 1792  3173]]


In [56]:
prob_rf = model_rf.predict_proba(X_test_selected)[:,1]
prob_dt = model_dt.predict_proba(X_test_selected)[:,1]
prob_lr = model.predict_proba(X_test_selected)[:,1]


In [57]:
final_prob = (
    0.4 * prob_lr +
    0.4 * prob_rf +
    0.2 * prob_dt
)

In [58]:
risk_score = (1 - final_prob) * 10
risk_score = risk_score.round(2)

In [59]:
print(risk_score[:10])

[5.93 5.34 4.52 5.81 5.22 4.32 8.04 7.49 2.93 6.19]


In [60]:
def risk_band(score):
    if score >= 8:
        return "Very Safe"
    elif score >= 6:
        return "Safe"
    elif score >= 5:
        return "Medium Risk"
    elif score >= 3:
        return "Risky"
    else:
        return "Very Risky"

risk_df["Risk Category"] = risk_df["Risk Score (out of 10)"].apply(risk_band)

risk_df.head(10)

NameError: name 'risk_df' is not defined